"""empty message

Revision ID: 252d27e0e43b
Revises: 8cd0b1de8f5e
Create Date: 2020-12-11 21:45:47.842021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252d27e0e43b'
down_revision = '8cd0b1de8f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('decks', sa.Column('creator', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'creator')
    op.alter_column('cards', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
