"""empty message

Revision ID: 8cd0b1de8f5e
Revises: 
Create Date: 2020-12-11 21:44:34.256060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd0b1de8f5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'creator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('creator', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
